languages:
  en: English
  es: Español
  jp: 日本語
templates:
  - name: Chla
cores:
  - name: aen
    sheets:
      - name: aen
        required: [eventID, cruiseNumber, stationName, eventTime, eventDate, decimalLatitude, decimalLongitude,bottomDepthInMeters]
        recommended: [eventRemarks,samplingProtocol,parentEventID, sampleLocation, pi_name, pi_email, pi_institution, recordedBy, sampleType]
        grouping: [required, event, storage,identification, description, measurement, trawl_or_net, ice, water, sediment, data, sample_responsible, comments ]
        terms:
          required: [eventID,parentEventID, cruiseNumber, stationName,eventDate, eventTime, decimalLatitude, decimalLongitude, bottomDepthInMeters]
          event: [ start_date, end_date,
            statID, recordNumber,
            sampleDepthInMeters, maximumDepthInMeters, minimumDepthInMeters,
            samplingProtocol, gearType, bottleNumber, sampleType]
          identification: [Taxon, phylum, class, order, family]
          description: [colour, smell, description, sampleVolumeInMilliliters, filteredVolumeInMilliliters]
          storage: [storageTemp,fixative]
          trawl_or_net: [middle_time, middleDecimalLatitude, middleDecimalLongitude, end_time, endDecimalLatitude, endDecimalLongitude, gonadWeightInGrams, liverWeightInGrams, somaticWeightInGrams, sex, maturationStage, ectoparasites, endoparasites]
          measurement: [individualCount, weightInGrams]
          water: [seaWaterAlkalinity, seaWaterChlorophyllA, seaWaterDeltaO18, seaWaterPH, seaWaterPOC, seaWaterPON, seaWaterPhaeopigment, seaWaterPressure, seaWaterSalinity, seaWaterTOC, seaWaterTemperatueInCelsius, seaWaterTotalDIC] 
          ice: [seaIceChlorophyllA, seaIceDeltaO18, seaIcePhaeopigment, seaIceTotalDIC, seaIceCoreType, seaIceCoreLengthInMeters, seaIceThicknessInMeters, seaIceFreeboardInMeters, seaIceMeltpondTemperatureInCelsius, seaIceMeltpondSalinity ]
          sediment: [sedimentChlorophyllA, sedimentPhaeopigment]
          data: [dataFilename]
          sample_responsible: [sampleLocation, recordedBy, pi_name, pi_email, pi_institution, pi_address ]
          comments: [occurrenceRemarks, fieldNotes, eventRemarks]
  - name: default
    sheets:
      - name: default
        required: [ occurrenceID, basisOfRecord, eventDate, scientificName ]
        recommended: [ occurrenceID, basisOfRecord, eventDate, kingdom, scientificName, taxonRank, decimalLatitude, decimalLongitude, geodeticDatum, coordinateUncertaintyInMeters, countryCode, individualCount, organismQuantity, organismQuantityType ]
        grouping: [ recordLevel, occurrence, event, location, identification, taxon, organism, other]
        terms:
          event: [eventID, parentEventID, fieldNumber, eventDate, eventTime, startDayOfYear,
            endDayOfYear, year, month, day, verbatimEventDate, habitat, samplingProtocol,
            sampleSizeValue, sampleSizeUnit, samplingEffort, fieldNotes, eventRemarks]
          identification: [identificationID, identificationQualifier, typeStatus, identifiedBy,
            dateIdentified, identificationReferences, identificationVerificationStatus, identificationRemarks]
          location: [locationID, higherGeographyID, higherGeography, continent, waterBody,
            islandGroup, island, country, countryCode, stateProvince, county, municipality,
            locality, verbatimLocality, minimumElevationInMeters, maximumElevationInMeters,
            verbatimElevation, minimumDepthInMeters, maximumDepthInMeters, verbatimDepth,
            minimumDistanceAboveSurfaceInMeters, maximumDistanceAboveSurfaceInMeters, locationAccordingTo,
            locationRemarks, decimalLatitude, decimalLongitude, geodeticDatum, coordinateUncertaintyInMeters,
            coordinatePrecision, pointRadiusSpatialFit, verbatimCoordinates, verbatimLatitude,
            verbatimLongitude, verbatimCoordinateSystem, verbatimSRS, footprintWKT, footprintSRS,
            footprintSpatialFit, georeferencedBy, georeferencedDate, georeferenceProtocol,
            georeferenceSources, georeferenceVerificationStatus, georeferenceRemarks]
          occurrence: [occurrenceID, catalogNumber, recordNumber, recordedBy, individualCount,
            organismQuantity, organismQuantityType, sex, lifeStage, reproductiveCondition,
            behavior, establishmentMeans, occurrenceStatus, preparations, disposition, associatedMedia,
            associatedReferences, associatedSequences, associatedTaxa, otherCatalogNumbers,
            occurrenceRemarks]
          organism: [organismID, organismName, organismScope, associatedOccurrences, associatedOrganisms,
            previousIdentifications, organismRemarks]
          other: [materialSampleID]
          recordLevel: [type, modified, language, license, rightsHolder, accessRights, bibliographicCitation,
            references, institutionID, collectionID, datasetID, institutionCode, collectionCode,
            datasetName, ownerInstitutionCode, basisOfRecord, informationWithheld, dataGeneralizations,
            dynamicProperties]
          taxon: [taxonID, scientificNameID, acceptedNameUsageID, parentNameUsageID, originalNameUsageID,
            nameAccordingToID, namePublishedInID, taxonConceptID, scientificName, acceptedNameUsage,
            parentNameUsage, originalNameUsage, nameAccordingTo, namePublishedIn, namePublishedInYear,
            higherClassification, kingdom, phylum, class, order, family, genus, subgenus,
            specificEpithet, infraspecificEpithet, taxonRank, verbatimTaxonRank, scientificNameAuthorship,
            vernacularName, nomenclaturalCode, taxonomicStatus, nomenclaturalStatus, taxonRemarks]

